name: deploy-gcp

on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: static-analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: venv cache
        uses: actions/cache@v3
        with:
          path: $HOME/venv
          key: requirements.txt-${{ hashFiles('src/requirements.txt') }}

      - name: setup venv
        run: |
          python3 -m venv $HOME/venv
          source $HOME/venv/bin/activate
          pip3 install --upgrade pip setuptools
          pip3 install -r requirements-test.txt
          pip3 install -r src/requirements.txt

      - name: flake8 + pylama
        run: |
          export PYTHONPATH=src:test:$PYTHONPATH
          source $HOME/venv/bin/activate
          flake8 src test
          cd src
          pylama
          cd ../test
          pylama

  dev-unit-test:
    name: dev-unit-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: venv cache
        uses: actions/cache@v3
        with:
          path: $HOME/venv
          key: requirements.txt-${{ hashFiles('src/requirements.txt') }}

      - name: setup venv
        run: |
          python3 -m venv $HOME/venv
          source $HOME/venv/bin/activate
          pip3 install --upgrade pip setuptools
          pip3 install -r requirements-test.txt
          pip3 install -r src/requirements.txt

      - name: pytest dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEVELOPMENT }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > config/dev-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=config/dev-service-account.json
          export PYTHONPATH=src:test:$PYTHONPATH
          source $HOME/venv/bin/activate
          pytest test

  dev-deployment:
    name: dev-deployment
    needs: [ static-analysis, dev-unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install into dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEVELOPMENT }}
        run: |
          cd src
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > service-account.json
          gcloud config list
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID_DEVELOPMENT }}
          gcloud config set functions/region us-central1
          gcloud config list
          gcloud functions delete save --quiet || true
          gcloud functions deploy save --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe save
          gcloud functions delete receive --quiet || true
          gcloud functions deploy receive --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe receive          
          gcloud functions delete transfer_backup --quiet || true
          gcloud functions deploy transfer_backup --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe transfer_backup          
          gcloud functions delete transfer_restore --quiet || true
          gcloud functions deploy transfer_restore --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe transfer_restore

  dev-deployment-test:
    name: dev-deployment-test
    needs: [ dev-deployment ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: test dev /save
        run: |
          status_code=$(curl -X POST --write-out %{http_code} \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_DEVELOPMENT }}.cloudfunctions.net/save \
            -H "Content-Type:application/json" \
            -d '{"code": "30000000e8", "digests": ["01234567", "12345678", "23456789"]}')
          if [[ "$status_code" -ne 200 ]] ; then
            echo 1
          else
            exit 0
          fi

      - name: test dev /receive
        run: |
          sleep 10
          digests=$(curl -X POST \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_DEVELOPMENT }}.cloudfunctions.net/receive \
            -H "Content-Type:application/json" \
            -d '{"code": "30000000e8"}')
          if [[ "${digests}" == "{\"digests\":[\"01234567\",\"12345678\",\"23456789\"]}" ]]; then
            echo 0
          else
            exit 1
          fi

      - name: test dev /transfer_backup
        run: |
          status_code=$(curl -X POST --write-out %{http_code} \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_DEVELOPMENT }}.cloudfunctions.net/transfer_backup \
            -H "Content-Type:application/json" \
            --data-binary "@test_data/transfer_backup_request.json")
          if [[ "$status_code" -ne 200 ]] ; then
            echo 1
          else
            exit 0
          fi

  prod-deployment:
    environment:
      name: gcp-production
      url: https://console.cloud.google.com/functions
    name: prod-deployment
    needs: [ dev-deployment-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install into prod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PRODUCTION }}
        run: |
          cd src
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > service-account.json
          gcloud config list
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID_PRODUCTION }}
          gcloud config set functions/region us-central1
          gcloud config list
          gcloud functions delete save --quiet || true
          gcloud functions deploy save --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe save
          gcloud functions delete receive --quiet || true
          gcloud functions deploy receive --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe receive          
          gcloud functions delete transfer_backup --quiet || true
          gcloud functions deploy transfer_backup --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe transfer_backup
          gcloud functions delete transfer_restore --quiet || true
          gcloud functions deploy transfer_restore --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account.json --runtime python39 --trigger-http --allow-unauthenticated
          gcloud functions describe transfer_restore

  prod-deloyment-test:
    name: prod-deloyment-test
    needs: [ prod-deployment ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: test prod /save
        run: |
          status_code=$(curl -X POST --write-out %{http_code} \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_PRODUCTION }}.cloudfunctions.net/save \
            -H "Content-Type:application/json" \
            -d '{"code": "30000000e8", "digests": ["0123456a", "1234567b", "2345678c"]}')
          if [[ "$status_code" -ne 200 ]] ; then
            echo 1
          else
            exit 0
          fi

      - name: test prod /receive
        run: |
          sleep 10
          digests=$(curl -X POST \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_PRODUCTION }}.cloudfunctions.net/receive \
            -H "Content-Type:application/json" \
            -d '{"code": "30000000e8"}')
          if [[ "${digests}" == "{\"digests\":[\"0123456a\",\"1234567b\",\"2345678c\"]}" ]]; then
            echo 0
          else
            exit 1
          fi

      - name: test prod /transfer_backup
        run: |
          status_code=$(curl -X POST --write-out %{http_code} \
            https://us-central1-${{ secrets.GCP_PROJECT_ID_PRODUCTION }}.cloudfunctions.net/transfer_backup \
            -H "Content-Type:application/json" \
            --data-binary "@test_data/transfer_backup_request.json")
          if [[ "$status_code" -ne 200 ]] ; then
            echo 1
          else
            exit 0
          fi